### PR TITLE
Talao

### PR DESCRIPTION
**Pull request by guix77**
Hi,

Lead dev of Talao.io here, we would love to join the alliance :)

We forked OriginProtocol's implementation of ERC 725 / 735 in our smart contracts: https://github.com/TalaoDAO/talao-contracts (should be deployed on Mainnet in a matter of days now).

Best,
Guillaume

### CODE REVIEW

**Review by joshfraser — COMMENTED** [review]
Mind using a Github link instead of LinkedIn? Trying to keep the focus on developers. 

Also, hotlinking an image from LinkedIn won't work.

**Review by joshfraser — APPROVED** [review]
Thanks. Sorry, can you fix the merge conflicts too?

**Comment by guix77** [comment]
Yup, doing it now :)

**Comment by guix77** [comment]
@joshfraser Thanks!

**Pull request merged**
